# This Dockerfile is used for building evictioner on https://connect.redhat.com
FROM openshift/origin-release:golang-1.11 as builder
#RUN yum update -y

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR /go/src/github.com/containers-ai/federatorai-agent
ADD . .

# Build
RUN make build

# Copy the Federator.ai Agent into a thin image
FROM registry.access.redhat.com/ubi7/ubi-minimal
ENV SUMMARY="Federator.ai Agent transmit metrics data to the Alameda server."	\
    DESCRIPTION="Federator.ai Agent transmit metrics data to the Alameda server." \
    NAME="Federator.ai Agent" \
    VERSION="latest" \
    USER_UID=1001 \
    USER_NAME=alameda \
    AIHOME=/opt/alameda/federatorai-agent

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$NAME" \
      com.redhat.component="customer-container" \
      name="$NAME" \
      version="$VERSION" \
      vendor="ProphetStor Data Services, Inc."

WORKDIR ${AIHOME}
COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/install_root.tgz /tmp/

RUN set -x \
    && microdnf update -y \
    && microdnf install -y \
        tar procps-ng psmisc findutils vim-minimal \
    && cd / && tar xzvf /tmp/install_root.tgz && rm -fv /tmp/install_root.tgz \
    && chown -R 1001:0 ${AIHOME} && chmod -R ug+w ${AIHOME} \
    && mkdir -p /var/log/alameda && chown -R 1001:0 /var/log/alameda && chmod ug+w /var/log/alameda

USER 1001
ENTRYPOINT ["/opt/alameda/federatorai-agent/bin/transmitter", "run"]
