# This Dockerfile is used for building evictioner on https://connect.redhat.com
FROM openshift/origin-release:golang-1.11 as builder
RUN yum update -y

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR /go/src/github.com/containers-ai/federatorai-agent

COPY . .

# Build
RUN ["/bin/bash", "-c", "GOOS=linux GOARCH=amd64 go build -ldflags \"-X main.VERSION=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD``git diff --quiet || echo '-dirty'` -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'\" -a -o ./transmitter/transmitter github.com/containers-ai/federatorai-agent/cmd"]
RUN ["/bin/bash", "-c", "CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -buildmode=plugin -a -o ./lib/inputlib/datapipe.so github.com/containers-ai/federatorai-agent/pkg/inputlib/alameda_datapipe"]
RUN ["/bin/bash", "-c", "CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -buildmode=plugin -a -o ./lib/outputlib/datapipe_recommender.so github.com/containers-ai/federatorai-agent/pkg/outputlib/alameda_recommender"]

# Copy the evictioner into a thin image
FROM registry.access.redhat.com/ubi7/ubi-minimal
ENV SUMMARY="Federator-AI Agent transmit prometheus metrics data to the Alameda server."	\
    DESCRIPTION="Federator-AI recommender transmit prometheus metrics data to the Alameda server." \
    NAME="Federator-AI Agent" \
    VERSION="latest" \
    USER_UID=1001 \
    USER_NAME=alameda

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$NAME" \
      com.redhat.component="customer-container" \
      name="$NAME" \
      version="$VERSION" \
      vendor="ProphetStor Data Services, Inc."


COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/etc/transmitter.toml /etc/alameda/federatorai-agent/transmitter.toml
COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/etc/input/datapipe.toml /etc/alameda/federatorai-agent/input/datapipe.toml
COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/etc/input/datapipe.toml /etc/alameda/federatorai-agent/output/datapipe.toml
COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/transmitter/transmitter /usr/local/bin/
COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/lib/inputlib/* /lib/inputlib/
COPY --from=builder /go/src/github.com/containers-ai/federatorai-agent/lib/outputlib/* /lib/outputlib/


RUN chown -R 1001:0 /etc/alameda && mkdir -p /var/log/alameda && chown -R 1001:0 /var/log/alameda && chmod ug+w /var/log/alameda

USER 1001
ENTRYPOINT ["/usr/local/bin/transmitter"]