[log]
 set-logcallers = true
 output-level = "debug" # debug, info, warn, error, fatal, none

[input_jobs]
    [input_jobs.datapipe_prometheus]
    name = "datapipe_prometheus"
    schedule-spec = "*/10 * * * * ?"
    lib-path = "/lib/inputlib/datapipe_prometheus.so"
    lib-configuration = "/etc/alameda/federatorai-agent/input/datapipe_prometheus.toml"

