[log]
 set-logcallers = false
 output-level = "debug" # debug, info, warn, error, fatal, none

[input_jobs]
    [input_jobs.cost_analysis_daily]
    name = "cost_analysis_daily"
    schedule-spec = "@every 1 hour"
    lib-path = "/lib/inputlib/costanalysis.so"
    lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_daily.toml"

    [input_jobs.cost_analysis_weekly]
    name = "cost_analysis_daily"
    schedule-spec = "@every 6 hour"
    lib-path = "/lib/inputlib/costanalysis.so"
    lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_weekly.toml"

    [input_jobs.cost_analysis_monthly]
    name = "cost_analysis_daily"
    schedule-spec = "@every 1 day"
    lib-path = "/lib/inputlib/costanalysis.so"
    lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_monthly.toml"