[log]
 set-logcallers = false
 output-level = "debug" # debug, info, warn, error, fatal, none

[input_jobs]
    [input_jobs.gpucollection]
    name = "gpu_collection"
    schedule-spec = "@every 3m"
    lib-path = "./lib/inputlib/prometheusgpu.so"
    lib-configuration = "/etc/alameda/federatorai-agent/input/influx_prometheus.toml"
