[log]
 set-logcallers = true
 output-level = "debug" # debug, info, warn, error, fatal, none

[input_jobs]
    [input_jobs.cost_analysis_daily]
    name = "cost_analysis_daily"
    schedule-spec = "* * */1 * * ?"
    lib-path = "/lib/inputlib/costanalysis.so"
    lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_daily.toml"


