apiVersion: v1
kind: ConfigMap
metadata:
  name: federatorai-agent-config
  namespace: federatorai-operator
data:
  transmitter.toml: |-
    [log]
     set-logcallers = false
     output-level = "info" # debug, info, warn, error, fatal, none

    [input_jobs]
        [input_jobs.cost_analysis_daily]
        name = "cost_analysis_daily"
        schedule-spec = "@every 1 hour"
        lib-path = "/lib/inputlib/costanalysis.so"
        lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_daily.toml"

        [input_jobs.cost_analysis_weekly]
        name = "cost_analysis_weekly"
        schedule-spec = "@every 6 hour"
        lib-path = "/lib/inputlib/costanalysis.so"
        lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_weekly.toml"

        [input_jobs.cost_analysis_monthly]
        name = "cost_analysis_monthly"
        schedule-spec = "@every 1 day"
        lib-path = "/lib/inputlib/costanalysis.so"
        lib-configuration = "/etc/alameda/federatorai-agent/input/cost_analysis_monthly.toml"

  cost_analysis_daily.toml: |
    [datahub]
      address = "alameda-datahub:50050"

    [datahub."retry-interval"]
      default = 3 # second

    [fedemeter]
      url = "http://fedemeter-api:8999/fedemeter-api/v1"
      username = ""
      password = ""

    [cost_analysis]
      calculate_current = true
      calculate_current_unit = "month"

    [recommendation]
      ri = true
      granularity = "3600"    # daily: 3600, weekly: 21600, monthly: 86400
      fill_days = "1"         # daily: 1, weekly: 7, monthly: 31

  cost_analysis_weekly.toml: |
    [datahub]
      address = "alameda-datahub:50050"

    [datahub."retry-interval"]
      default = 3 # second

    [fedemeter]
      url = "http://fedemeter-api:8999/fedemeter-api/v1"
      username = ""
      password = ""

    [cost_analysis]
      calculate_current = false
      calculate_current_unit = "month"

    [recommendation]
      ri = true
      granularity = "21600"    # daily: 3600, weekly: 21600, monthly: 86400
      fill_days = "7"         # daily: 1, weekly: 7, monthly: 31

  cost_analysis_monthly.toml: |
    [datahub]
      address = "alameda-datahub:50050"

    [datahub."retry-interval"]
      default = 3 # second

    [fedemeter]
      url = "http://fedemeter-api:8999/fedemeter-api/v1"
      username = ""
      password = ""

    [cost_analysis]
      calculate_current = false
      calculate_current_unit = "month"

    [recommendation]
      ri = true
      granularity = "86400"    # daily: 3600, weekly: 21600, monthly: 86400
      fill_days = "31"         # daily: 1, weekly: 7, monthly: 31

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-agent
  namespace: federatorai-operator
spec:
  selector:
    matchLabels:
      app: federatorai-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: federatorai-agent
    spec:
      containers:
      - name: federatorai-agent
        image: docker-registry.default.svc:5000/federatorai-agent/transmitter:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/transmitter.toml
            subPath: transmitter.toml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/cost_analysis_daily.toml
            subPath: cost_analysis_daily.toml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/cost_analysis_weekly.toml
            subPath: cost_analysis_weekly.toml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/cost_analysis_monthly.toml
            subPath: cost_analysis_monthly.toml
      volumes:
        - name: federatorai-agent-config
          configMap:
            name: federatorai-agent-config
