apiVersion: v1
kind: ConfigMap
metadata:
  name: federatorai-agent-config
  namespace: federatorai-agent
data:
  transmitter.yml: |-
    log:
      set-logcallers: true
      output-level: "debug" # debug, info, warn, error, fatal, none

    input_jobs:
    - name: "datahub"
      schedule-spec: "*/5 * * * * ?"
      lib-path: "/lib/inputlib/datapipe.so"
      lib-configuration: "/etc/alameda/federatorai-agent/inputlib/datapipe.yml"
  datapipe.yml: |
    log:
      set-logcallers: true
      output-level: "debug" # debug, info, warn, error, fatal, none

    input_jobs:
    - name: "datahub"
      schedule-spec: "*/5 * * * * ?"
      lib-path: "/lib/inputlib/datapipe.so"
      lib-configuration: "/etc/alameda/federatorai-agent/inputlib/datapipe.yml"
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: federatorai-agent
  namespace: federatorai-agent
spec:
  selector:
    matchLabels:
      app: federatorai-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: federatorai-agent
    spec:
      containers:
      - name: federatorai-agent
        image: docker-registry.default.svc:5000/federatorai-agent/transmitter:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/transmitter.yml
            subPath: transmitter.yml
          - name: federatorai-agent-config
            mountPath: /etc/alameda/federatorai-agent/input/datapipe.yml
            subPath: datapipe.yml
      volumes:
        - name: federatorai-agent-config
          configMap:
            name: federatorai-agent-config
          items:
            - key: transmitter.yml
              path: transmitter.yml
            - key: datapipe.yml
              path: datapipe.yml
