[datahub]
address = "54.218.143.157:30946"

[datahub."retry-interval"]
default = 3 # second

[fedemeter]
url = "http://54.218.143.157:31000/fedemeter-api/v1"
username = ""
password = ""

[cost_analysis]
calculate_current = false
calculate_current_unit = "month"

[recommendation]
ri = true
granularity = "21600"    # daily: 3600, weekly: 21600, monthly: 86400
fill_days = "7"         # daily: 1, weekly: 7, monthly: 31

